var lesdatasbiens=`[
    {
       "id":1,
       "typedebien":"Maison",
       "ville":"Saint-Die-Des-Vosges",
       "cp":88100,
       "rue":"11 rue de l'université",
       "superficieint":200,
       "superficieext":100,
       "nbdepiece":10,
       "typedecontrat":"Vente",
       "prix":230000,
       "img1":"maisonext1.jpg",
       "img2":"maisonint1.jpg",
       "img3":"maisonsdb1.jpg",
       "img4":"maisonchb1.jpg",
       "description":"Rénovée à neuf, cette maison vous offrira une cuisine toute équpée, une salle de bain avec sa douche à l'italienne, ainsi qu'une suite parentale et esapce dressing."
    },
    {
       "id":2,
       "typedebien":"Maison",
       "ville":"Epinal",
       "cp":88000,
       "rue":"79 chemin de la Taviane",
       "superficieint":105,
       "superficieext":59,
       "nbdepiece":5,
       "typedecontrat":"Type de contract: Location",
       "prix":52,
       "img1":"maisonext2.jpg",
       "img2":"maisonint2.jpg",
       "img3":"maisonsdb2.jpg",
       "img4":"maisonchb2.jpg",
       "description":"Habitiat très agréable pour séjours en famille, avec une grande terrasse présente à l'extérieur. La cuisine est équipée des dernières fonctionnalités et ouverte sur la salle à manger. Chambres d'une taille modeste avec une salle de bain et des WC."
    },
    {
       "id":3,
       "typedebien":"Type: Appartement",
       "ville":"Bordeaux",
       "cp":33150,
       "rue":"4 rue de la concorde",
       "superficieint":75,
       "superficieext":5,
       "nbdepiece":"F2",
       "typedecontrat":"Location",
       "prix":1075,
       "img1":"appartement3.jpg",
       "img2":"appartementint3.jpg",
       "img3":"appartementsdb3.jpg",
       "img4":"appartementchb3.jpg",
       "description":"Cet appartement se situe au 3ème étage de l'immeuble, immeuble équipé d'un ascenceur, deux chambres de 10m² chacune, d'une cuisine équipée et d'une salle de bain avec baignoire."
    },
    {
       "id":4,
       "typedebien":"Appartement",
       "ville":"Epinal",
       "cp":88000,
       "rue":"22 rue Neuve Grange",
       "superficieint":46,
       "superficieext":3,
       "nbdepiece":"F1",
       "typedecontrat":"Location",
       "prix":285,
       "img1":"appartement4.jpg",
       "img2":"appartementint4.jpg",
       "img3":"appartementsdb4.jpg",
       "img4":"appartementchb4.jpg",
       "description":"Appartement avec vue agréable sur les parcs alentours, il est équipé d'une cuisine modeste, de WC et d'une salle de bains avec une douche et une baignoire."
    },
    {
       "id":5,
       "typedebien":"Maison",
       "ville":"Grenoble",
       "cp":75015,
       "rue":"8 bis rue de l'Arrivée",
       "superficieint":155,
       "superficieext":25,
       "nbdepiece":7,
       "typedecontrat":"Vente",
       "prix":1254000,
       "img1":"maisonext5.jpg",
       "img2":"maisonint5.jpg",
       "img3":"maisonsdb5.jpg",
       "img4":"maisonchb5.jpg",
       "description":"Maison d'une grande taille possédant le confort et la sérénité. Equipée des dernières fonctionnalités numériques, elle est composée de 7 pièces aussi grandes les unes que les autres."
    }
 ]`;